### ISSUE TITLE
バリ島の観光名所が知りたい

### ISSUE THREAD

**Issue by usa619** [usa619/bali-trip#2]
## WHY
- 海に飽きた時の逃げ場を用意したい
- 実は普通に面白そうなところがあるかも

## WHAT
良い悪いの精度は低くても良いので、可能性としてあるものを上げていく

**Comment by usa619** [comment]
@tomoki11 1コメント、1施設の感じで書いてって

**Comment by tomoki11** [comment]
## [ウルワッ寺院](http://www.balitouryokou.com/sightseen/pura_uluwatu.html)
>南西に位置する岬。天気と時間帯が合えばめっちゃ綺麗なsunset見れる。ビーチで海の眺めを満喫できればいらないかも。

**Comment by tomoki11** [comment]
## [タマンアユン寺院](http://bali.navi.com/miru/96/)
>バリ島でもっとも優美な寺院。そんな遠くない。ウルワッ寺院よりも近いかも

**Comment by tomoki11** [comment]
## [クタ・レギャンビーチ](http://www.baliheat.com/home/news_info/area/kuta_legian/)
>ホテルから一番近いのがレギャンビーチで、北側。結構落ち着いてる雰囲気で波も穏やかな時があるらしい。  クタビーチは近くに繁華街があって、ショッピングとかにも行ける。

どっちも夕日とかの景色は最高のなはず

**Comment by usa619** [comment]
結局、どこも行かなかった。観光しないことを目標にしていたので、良かった
