### ISSUE TITLE
バリ島でしたいことを書いていく

### ISSUE THREAD

**Issue by usa619** [usa619/bali-trip#3]
## WHY
`これやっておけばよかった。。` みたいなことをなくすため

## WHAT
荒い粒度で書き出していって、個別に考えた方が良さそうなものは別Issueとして立てる。

**Comment by usa619** [comment]
## スキューバーダイビング

**Comment by chachmaru** [comment]
# ストリップ
年確厳しいかなぁ

**Comment by usa619** [comment]
## マッサージ

**Comment by usa619** [comment]
スキューバーダイビングとマッサージが達成できた
