### ISSUE TITLE
スキューバーダイビングがしたい

### ISSUE THREAD

**Issue by usa619** [usa619/bali-trip#5]
## WHY
- 楽しそう
- バリ島は泳ぐよりも海系のアクティビティをやった方が楽しめそう

## HOW
いけそうなところを探す

**Comment by tomoki11** [comment]
[スキューバダイビングのサイト](http://bali-oh.com/diving.html)見てたら、クッソ行きたくなった
このサイトだと中級以上向けだけど、ヌサペニダ島で大物見たい

**Comment by usa619** [comment]
> ヌサペニダ島

@tomoki11 バリ島から別の島行くパターンのやつ？？

**Comment by tomoki11** [comment]
@usa619 そそ、隣にある小さい島。
他のサイトでもその島に行く体験ダイビングとかあったよ。
お金はまだ見てないけど笑

**Comment by usa619** [comment]
@tomoki11 まあ基本やる方向で！予約とか必要な可能性もあるから早めにpickできるといいね

**Comment by tomoki11** [comment]
@usa619 ある程度調べて後でいくつか候補あげるね〜

**Comment by tomoki11** [comment]
##[バリインターダイブ](http://www.bali-diving.com/html_4_b_course_price.html)

US150ぐらいだね

**Comment by tomoki11** [comment]
## [バリ王のツアー](http://tour.bali-oh.com/opt/optional_list.php?TOP=2&S=SCH&order=0&area=&mokuteki=39&time=&icon_flg=&keyword=%C2%CE%B8%B3&car=&answer=)

値段は同じくらいかな

**Comment by tomoki11** [comment]
## [VELTRA](http://www.veltra.com/jp/asia/indonesia/bali/date_search/20160501/ctg/160120:Scuba_Diving/)

どの日に行っても、３つのプランどれでもできそう。

**Comment by tomoki11** [comment]
とりま３つほどサイトをあげたけど、色々プランあるね

**Comment by tomoki11** [comment]
## [Ocean Life Bari](http://oceanlifebali.com/introdiving.htm)

他と同じような感じ

**Comment by usa619** [comment]
ヌサドゥアのアポロというところでした。海の透明度はイマイチだった。　同じ場所でバナナボートなどができた点は良かった
