### ISSUE TITLE
ホテル代と飛行機代をusa619の口座に振り込んでほしい

### ISSUE THREAD

**Issue by usa619** [usa619/bali-trip#6]
184650円 (振込手数料含めず)

- [x] @tomoki11
- [ ] @chachmaru

**Comment by tomoki11** [comment]
今日親に頼んで、明日、振り込まれるはず

**Comment by usa619** [comment]
@tomoki11 ありがとう！

**Comment by usa619** [comment]
@chachmaru ping

**Comment by chachmaru** [comment]
@usa619 pong わり、完全に失念してた、明日がんばる

**Comment by usa619** [comment]
振り込まれたので、close
