### ISSUE TITLE
海外旅行用保険に入る

### ISSUE THREAD

**Issue by usa619** [usa619/bali-trip#7]
## WHY
一応ね

## WHAT

全員 :ballot_box_with_check: になったらcloseする
各自一応、自分が入った保険の内容をコメントで書く

### checklist

- [x] @usa619
- [x] @chachmaru
- [x] @tomoki11

**Comment by tomoki11** [comment]
どうやって入るん？
保険何もわかんね

**Comment by usa619** [comment]
@tomoki11 親に確認したほうがいいかも！ クレジットカードとか生命保険とか選択肢的にはあったはず。

**Comment by usa619** [comment]
自分は楽天カードの付帯のものを使った。楽天カードは旅行に行く際の交通機関で楽天カードを使用すると保険がつけるようになる
