### ISSUE TITLE
持ち物

### ISSUE THREAD

**Issue by usa619** [usa619/bali-trip#9]
# @usa619
### 衣類
- [x] パンツ x6
- [x] Tシャツ x3
- [x] ポロシャツ x2
- [x] パジャマ用半ズボン x2
- [x] 薄手のパーカー
- [x] 半ズボン x1
- [x] 水着

### ガジェット
- [x] 50mm
- [x] 予備バッテリー x1
- [x] カメラ充電器
- [x] iPhone防水ケース
- [x] 変換フラグ //Cタイプ

> カメラやパソコンをバリで充電する場合、充電器やアダプタに「100V」 と書いてある場合は変圧器とプラグが必要です。もし「100V - 240V 」と書いてある場合は変圧器は必要なく、プラグだけで充電できます。プラグは丸ピン2本のCタイプで日本の電気屋さんで２００円くらい、バリ島ではホームセンターで１００円くらいで売っています

### その他
- [x] 日焼け止め x2 (@chachmaru の分も)
- [x] 歯ブラシ
- [x] シェーバー
- [x] サンダル
- [x] 折りたたみ傘

## バックパック
- [x] カメラ本体
- [x] 12-40mm
- [x] SDカード x2
- [x] ネックピロー
- [x] MacBook
- [x] MacBook 充電器
- [ ] マスク //機内保湿用
- [x] パスポート
- [ ] 外貨用財布
	- [ ] クレジットカード

## @tomoki11 
- [x] 正露丸
- [x] 虫除け //塗りタイプ
- [x] 痒み止め
- [x] サングラス x3
- [x] iPhone防水ケース x3

**Comment by usa619** [comment]
@tomoki11 @chachmaru 持ってくもの書いてって！

**Comment by usa619** [comment]
@tomoki11 持ってたら、これ持ってきてほしいんだけど
>- [ ] 正露丸
- [ ] 虫除け //塗りタイプ
- [ ] 痒み止め

**Comment by tomoki11** [comment]
@usa619 了解、持ってけると思う〜
さがしてみるけど正露丸じゃなくても整腸剤とかでいいっしょ？

**Comment by usa619** [comment]
> も整腸剤とかでいいっしょ？

🙆

**Comment by tomoki11** [comment]
ドルって最低何ドル必要？
観光ビザ代[25$)だけでおけ？

**Comment by tomoki11** [comment]
http://www.balitouryokou.com/aboutbali/imigre.html

ビザ代いらなそう

**Comment by usa619** [comment]
@tomoki11 天才だった (僕の読んだ記事が廃止前のものだったみたい

**Comment by chachmaru** [comment]
@usa619 @tomoki11 
レジャーシート 1.8m x 1.6m
大きめのうきわ x1
すいかボール x1
持ってくね

**Comment by usa619** [comment]
特に不足はなかったが、Tシャツはもうちょっと持って行った方が良さそうだった。1日2枚ぐらいあると何も考えずに着れそう
